### ISSUE TITLE
empty "progress" screen on first login

### ISSUE THREAD

**Issue by srmadden** [CSAIL-LivingLab/getfit#3]
The "progress" screen should show some helpful message like "Your exercise history will be shown here after you record your first activity", instead of three headings with no content between them when the user first logs in.

**Comment by RogerTangos** [comment]
Sorry - this feature was working just before release, and isn't anymore. I'll add it back in. The iOS JS is driving me up the wall.

**Comment by RogerTangos** [comment]
Closed in https://github.com/CSAIL-LivingLab/getfit/commit/448a4c65070142857184ff5c76690e6b051a327b. Screen size bugfix in https://github.com/CSAIL-LivingLab/getfit/commit/af3d65b714892dc52dc139f446d5232a138d4689
