### ISSUE TITLE
should default to "donate sensor data to csail" on

### ISSUE THREAD

**Issue by srmadden** [CSAIL-LivingLab/getfit#4]
This checkbox should default on.  We should include an explanatory note below it, rather than showing the alert when the user enables it.

**Comment by RogerTangos** [comment]
I thought that the design was to have the user opt-in?

The reason that the alert shows is that we can only ask for location permission once. 
https://medium.com/@mulligan/the-right-way-to-ask-users-for-ios-permissions-96fa4eb54f2c

potential solution: Put the switch on the 2nd introductory page, with the default on. Have the alert triggered by the "Go To GetFit" button, and then have the alert close the modal. What do you think?

This one is kind of low priority, considering that it works as is.

**Comment by RogerTangos** [comment]
Resolved in  0fb3d0564902ba2982d95c5b5959536c5d5c4c2d. The box is checked, on the intro screen, but sensing doesn't actually start until they hit next
